import Navbar from "@/components/Navbar";
import Products from "@/components/Products";
import { redirect } from "next/navigation";

export const metadata = {
  title: "شركة قمم المساحة التجارية",
  description: "Generated by create next app",
};

const page = ({ params }) => {
  const categoryName = params.categname;

  if (categoryName === "opts" || categoryName === "rbt" || categoryName === "cors") redirect(`/products/${categoryName}/details/0`);
  return (
    <>
      <Navbar isHomePage={false} />
      <div className="flex flex-wrap items-center justify-center gap-4 w-full mt-36">
        <Products 
          title={categoryName}
          isAcc={categoryName === "accessory" && true}
        />
      </div>
    </>
  );
};

export default page;
