import Footer from "@/components/Footer";
import Testimonials from "@/components/Testimonials";
import Navbar from "@/components/Navbar";
import WhyUS from "@/components/WhyUS";
import Details from "@/components/Details";
import About from "@/components/About";
import Contacts from "@/components/Contacts";

export const metadata = {
  title: "من نحن",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Navbar isHomePage={false} />
      <section style={{ margin: "100px 0" }}>
        <About />
        <WhyUS />
        {/* <Testimonials /> */}
        <Contacts />
      </section>
      <Footer />
    </>
  );
};

export default page;
