import Details from "@/components/Details";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Navbar from "@/components/Navbar";
import Map from "@/components/Map";
import Statistics from "@/components/Statistics";
import Partners from "../components/Partners";
import Projects from "../components/Projects";
import Contacts from "@/components/Contacts";
import Testimonials from "@/components/Testimonials";
import WhyUS from "@/components/WhyUS";

export const metadata = {
  title: "الرئيسية",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      <Navbar isHomePage={true}  />
      <Hero />
      {/* <Details isHome={true} /> */}
      <WhyUS isHome={true} />
      <Partners />
      <Projects />
      <Statistics />
      <WhyUS />
      <Testimonials />
      <Contacts />
      <Map />
      <Footer />
    </>
  );
}
