import Navbar from "@/components/Navbar";
import Product from "@/components/Product";

export const metadata = {
  title: "شركة قمم المساحة التجارية",
  description: "Generated by create next app",
};

const page = async ({ params }) => {
  const categoryName = params.categname;
  const id = params.id;

  return (
    <>
      <Navbar isHomePage={false} />
      <div className="flex flex-wrap items-center justify-center gap-4 w-full mt-36">
        <Product
          categoryName={categoryName}
          ID={Number(id)}
        />
      </div>
    </>
  );
};

export default page;
