import Navbar from "@/components/Navbar";
import Contacts from "@/components/Contacts";
import Map from "@/components/Map";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";

export const metadata = {
  title: "تواصل معنا",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <Navbar isHomePage={false} />
      <section style={{marginTop: "100px"}}>
      <Contacts />
      <Map />
      </section>
      <Footer />
    </>
  );
};

export default page;
